<?php


require '../../PHPMailer/src/Exception.php';
require '../../PHPMailer/src/PHPMailer.php';
require '../../PHPMailer/src/SMTP.php';

require '../../PHPMailer/src/OAuth.php';

use PHPMailer\PHPMailer\PHPMailer;


use PHPMailer\PHPMailer\Exception;

session_start();
include('../Database/Connection.php'); // Inclusão do arquivo para conectar ao Banco de Dados



if(empty($_POST['redefinirEmail'])) { // Verifica se o campo de email está vazio
	$_SESSION['campoVazio'] = true; // Caso ele estiver vazio, redireciona para o login com a sessão campoVazio
	 header("Location: ../../redefinir.php");// Exibindo um alerta "Digite o email!"
	exit();
}
// Definição das variáveis dos campos de email
$email = $_POST['redefinirEmail'];

//Bloco do email que irá enviar o email de redefinição

$novasenha = substr(md5(time()),0,6);
$mail = new PHPMailer;
$mail->isSMTP();
$mail->SMTPAuth = true;

$mail->Host = 'smtp-mail.outlook.com';
$mail->Username = 'edcsys@hotmail.com'; //paste one generated by Mailtrap
$mail->Password = 'educsys123'; //paste one generated by Mailtrap
$mail->SMTPSecure = 'tls';
$mail->Port = 587;
$mail->setFrom('edcsys@hotmail.com');

$mail->Subject = 'Redefinicao de Senha | EdSys';

$mailContent = "

Foi solicitada uma redefinição de senha
    
    Sua nova senha:   ".$novasenha."";
$mail->Body = $mailContent;
$mail->addAddress($_POST['redefinirEmail']);


//Fim bloco

// Aqui são os queries para selecionar cada tabela

 $queryALUNOS = mysqli_query($conn, "SELECT * FROM Login_Aluno WHERE Email='$email'"); // Query do SQL

  $rowsALUNOS = mysqli_num_rows($queryALUNOS); // Variável para o número de registros


	$queryFUNC = mysqli_query($conn, "SELECT * FROM Login_Secretaria WHERE Email='$email'"); // Query do SQL

   $rowsFUNC = mysqli_num_rows($queryFUNC); // Variável para o número de registros

	 $queryProf = mysqli_query($conn, "SELECT * FROM Login_Prof WHERE Email='$email' "); // Query do SQL

    $rowsProf = mysqli_num_rows($queryProf); // Variável para o número de registros




	 $queryResp = mysqli_query($conn, "SELECT * FROM Login_Resp WHERE Email='$email'"); // Query do SQL

    $rowsResp = mysqli_num_rows($queryResp); // Variável para o número de registros





// Aqui começa um block de if elses, onde se não existir registro de uma tabela, irá buscar por outra e outra, caso nenhuma apareça
    // será reconhecido como login inválido ou errado


  if($rowsALUNOS == 1){ //Primeiro if de ALUNOS



if(!$mail->send()){ // Caso o email não seja enviado
		$_SESSION['emailNaoEnviado'] = true;
		 header("Location: ../../redefinir.php");

			exit();
}
else{ // Caso seja enviado, irá enviar o email com a nova senha e alterá-la automaticamente no sistema
		
	$passChange =  mysqli_query($conn, "UPDATE Login_Aluno SET Senha='$novasenha' WHERE Email='$email'");
	$_SESSION['emailEnviado'] = true;
		 header("Location: ../../redefinir.php");

			exit();
}

	exit();
  }


	else if($rowsFUNC ==1){ // If else de FUNCIONARIOS
		


if(!$mail->send()){ // Caso o email não seja enviado
		$_SESSION['emailNaoEnviado'] = true;
		 header("Location: ../../redefinir.php");

			exit();
}
else{ // Caso seja enviado, irá enviar o email com a nova senha e alterá-la automaticamente no sistema
		
	$passChange =  mysqli_query($conn, "UPDATE Login_Secretaria SET Senha='$novasenha' WHERE Email='$email'");
	$_SESSION['emailEnviado'] = true;
		 header("Location: ../../redefinir.php");

			exit();
}

			exit();
	}

	else if($rowsProf ==1){ // else if de Professores
		


if(!$mail->send()){ // Caso o email não seja enviado
		$_SESSION['emailNaoEnviado'] = true;
		 header("Location: ../../redefinir.php");

			exit();
}
else{ // Caso seja enviado, irá enviar o email com a nova senha e alterá-la automaticamente no sistema
		
	$passChange =  mysqli_query($conn, "UPDATE Login_Prof SET Senha='$novasenha' WHERE Email='$email'");
	$_SESSION['emailEnviado'] = true;
		 header("Location: ../../redefinir.php");

			exit();
}

			exit();
	}
	else if($rowsResp ==1){ // If else de responsáveis
		

if(!$mail->send()){ // Caso o email não seja enviado
		$_SESSION['emailNaoEnviado'] = true;
		 header("Location: ../../redefinir.php");

			exit();
}
else{ // Caso seja enviado, irá enviar o email com a nova senha e alterá-la automaticamente no sistema
		
	$passChange =  mysqli_query($conn, "UPDATE Login_Resp SET Senha='$novasenha' WHERE Email='$email'");
	$_SESSION['emailEnviado'] = true;
		 header("Location: ../../redefinir.php");

			exit();
}

			exit();
	}


// Caso não encontre nada
  else
  {

		$_SESSION['noEmail'] = true; // Caso a cadeia de if's chegue aqui, é porque não apareceu nenhum registro
		header("Location: ../../redefinir.php"); // Logo, as credenciais estão erradas ou não existe,m e irá voltar ao login cm a sessão nao_autenticado
		exit();  } // Exibindo um alerta de usuario ou senha errados

  mysqli_close($conn); // Fechando conexão





 ?>
